CREATE DATABASE IF NOT EXISTS finpro;
USE finpro;

CREATE TABLE IF NOT EXISTS files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  filename VARCHAR(1024) NOT NULL,
  filepath VARCHAR(2048) NOT NULL,
  size BIGINT NOT NULL,
  uploaded_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS accounts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Pastikan user dan hak akses
CREATE USER IF NOT EXISTS 'finpro_user'@'%' IDENTIFIED BY 'finpro_pass';
GRANT ALL PRIVILEGES ON finpro.* TO 'finpro_user'@'%';
FLUSH PRIVILEGES;
